name: ML Run

on:
  push:
    branches:
      - main

jobs:
  ml_run:
    runs-on: ubuntu-latest
    container:
      image: jupyter/scipy-notebook:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: run script
        run: python ml_example.py